### ISSUE TITLE
Update Packagist and API Docs

### ISSUE THREAD

**Issue by AntoninoBonanno** [kasparsj/scopus-api-php#5]
Hi @kasparsj,
I noticed that in [Packagist](https://packagist.org/packages/kasparsj/scopus-search-api) there is no auto-update set, it would be nice to enable it so all changes to the master will be released.

In addition, the documentation on [GitHub Page](https://kasparsj.github.io/scopus-api-php/) is not up to date (for example, `Scopus\Response\AbstractCitations` is missing)

Thanks

**Comment by matasarei** [comment]
The issue is still actual. Version 1.3 is not available on Packagist.

**Comment by kasparsj** [comment]
fixed. sorry for delay.
